In [1]:
from larlib import *
V = [[0, 0], [1, 0], [2, 0], [0, 1], [1, 1], [2, 1]]
FV = [[0, 1, 3], [1, 2, 4], [1, 3, 4], [2, 4, 5]]
EV = [[0,1],[0,3],[1,2],[1,3],[1,4],[2,4],[2,5],[3,4],[4,5]]

Evaluating fenvs.py..
...fenvs.py imported in 0.0211292958083 seconds


c:\programmi\python27\lib\site-packages\larlib\larstruct.py:233: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  self.body = [item for item in data if item != None]


In [2]:
VIEW(STRUCT(MKPOLS((V,FV))))


<pyplasm.xgepy.Hpc; proxy of <Swig Object of type 'std::shared_ptr< Hpc > *' at 0x0000000014196810> >

![1.PNG](files/Immagini/1.PNG)

In [3]:
k=MKPOLS([V,FV])

In [4]:
VIEW(STRUCT(k))


<pyplasm.xgepy.Hpc; proxy of <Swig Object of type 'std::shared_ptr< Hpc > *' at 0x0000000014196CF0> >

![2.PNG](files/Immagini/2.PNG)

![immagine.png](files/Immagini/immagine.png)


QUESTO TIPO DI ERRORE SI RIPARA USANDO STRUCT PER POTER PASSARE AL SISTEMA UN SOLO ARGOMENTO ( QUELLO RICHIESTO PER POTER GESTIORE LE ECCEZIONI)

In [5]:
VIEW(EXPLODE(1.2,1.2,1)(MKPOLS((V,FV))))

<pyplasm.xgepy.Hpc; proxy of <Swig Object of type 'std::shared_ptr< Hpc > *' at 0x00000000141AB120> >

![3.PNG](files/Immagini/3.PNG)

In [6]:
VIEW(STRUCT(MKPOLS((V,EV)))); VIEW(EXPLODE(1.2,1.2,1)(MKPOLS((V,EV))))

<pyplasm.xgepy.Hpc; proxy of <Swig Object of type 'std::shared_ptr< Hpc > *' at 0x00000000141AB330> >

![4.PNG](files/Immagini/4.PNG)

In [10]:
csrFV = csrCreate(FV)
csrEV = csrCreate(EV)
print "\ncsrCreate(FV) =\n", csrFV
print "\n>>> csr2DenseMatrix"
print "\nFV =\n", csr2DenseMatrix(csrFV)
print "\nEV =\n", csr2DenseMatrix(csrEV)


csrCreate(FV) =
  (0, 0)	1
  (0, 1)	1
  (0, 3)	1
  (1, 1)	1
  (1, 2)	1
  (1, 4)	1
  (2, 1)	1
  (2, 3)	1
  (2, 4)	1
  (3, 2)	1
  (3, 4)	1
  (3, 5)	1

>>> csr2DenseMatrix

FV =
[[1 1 0 1 0 0]
 [0 1 1 0 1 0]
 [0 1 0 1 1 0]
 [0 0 1 0 1 1]]

EV =
[[1 1 0 0 0 0]
 [1 0 0 1 0 0]
 [0 1 1 0 0 0]
 [0 1 0 1 0 0]
 [0 1 0 0 1 0]
 [0 0 1 0 1 0]
 [0 0 1 0 0 1]
 [0 0 0 1 1 0]
 [0 0 0 0 1 1]]


MATRICE SPARSA CON 12 ELEMENTI