In [5]:
from larlib import *

In [6]:
V = [[0,0],[1,0],[2,0],[0,1],[1,1],[2,1]]
FV = [[0, 1, 3], [1, 2, 4],[1, 3, 4], [2, 4, 5]]
EV = [[0,1],[0,3],[1,2],[1,3],[1,4],[2,4],[2,5],[3,4],[4,5]]
VIEW(STRUCT(MKPOLS((V,FV))))
VIEW(EXPLODE(1.2,1.2,1)(MKPOLS((V,FV))))
VIEW(STRUCT(MKPOLS((V,EV))))
VIEW(EXPLODE(1.2,1.2,1)(MKPOLS((V,EV))))

csrFV = csrCreate(FV)
csrEV = csrCreate(EV)

print "\ncsrCreate(FV) =\n", csrFV
print "\n>>> csr2DenseMatrix"
print "\nFV = \n", csr2DenseMatrix(csrFV)
print "\nEV = \n", csr2DenseMatrix(csrEV)


csrCreate(FV) =
  (0, 0)	1
  (0, 1)	1
  (0, 3)	1
  (1, 1)	1
  (1, 2)	1
  (1, 4)	1
  (2, 1)	1
  (2, 3)	1
  (2, 4)	1
  (3, 2)	1
  (3, 4)	1
  (3, 5)	1

>>> csr2DenseMatrix

FV = 
[[1 1 0 1 0 0]
 [0 1 1 0 1 0]
 [0 1 0 1 1 0]
 [0 0 1 0 1 1]]

EV = 
[[1 1 0 0 0 0]
 [1 0 0 1 0 0]
 [0 1 1 0 0 0]
 [0 1 0 1 0 0]
 [0 1 0 0 1 0]
 [0 0 1 0 1 0]
 [0 0 1 0 0 1]
 [0 0 0 1 1 0]
 [0 0 0 0 1 1]]


![1.PNG](files/Immagini/1.PNG)
![2.PNG](files/Immagini/2.PNG)
![3.PNG](files/Immagini/3.PNG)
![4.PNG](files/Immagini/4.PNG)

In [7]:
def larSimplexFacets(simplices):
    out = []
    d = len(simplices[0])
    for simplex in simplices:
        out += [simplex[0:k]+ simplex[k+1:d]
               for k in range(d)]
        out = sorted(out)
        return[facet for k, facet in enumerate(out[:-1])
              if out[k] != out[k+1]] + [out[-1]]

In [8]:
larSimplexFacets([[0]])

[[]]

In [9]:
larSimplexFacets([[0,1]])

[[0], [1]]

In [10]:
larSimplexFacets([[0,1,2]])

[[0, 1], [0, 2], [1, 2]]

In [11]:
larSimplexFacets([[0,1,2,3]])

[[0, 1, 2], [0, 1, 3], [0, 2, 3], [1, 2, 3]]

In [12]:
larSimplexFacets([[0,1,2,3,4]])

[[0, 1, 2, 3], [0, 1, 2, 4], [0, 1, 3, 4], [0, 2, 3, 4], [1, 2, 3, 4]]

In [13]:
V, CV = larSimplexGrid1([1,1,1])
VIEW(EXPLODE(1.5,1.5,1.5)(MKPOLS((V,CV))))
SK2 = (V,larSimplexFacets(CV))
VIEW(EXPLODE(1.5,1.5,1.5)(MKPOLS(SK2)))
SK1 = (V,larSimplexFacets(SK2[1]))
VIEW(EXPLODE(1.5,1.5,1.5)(MKPOLS(SK1)))

V,CV = larSimplexGrid1([5,5,2])

![5.PNG](files/Immagini/5.PNG)
![6.PNG](files/Immagini/6.PNG)
![7.PNG](files/Immagini/7.PNG)

In [14]:
def boundary(cells,facets):
    csrCV = csrCreate(cells)
    csrFV = csrCreate(facets)
    csrFC = matrixProduct(csrFV,csrTranspose(csrCV))
    facetLenghts = [csrCell.getnnz() for csrCell in csrCV]
    return csrBoundaryFilter(csrFC,facetLengths)

def coboundary(cells,facets):
    Boundary = boundary(cells,facets)
    return csrTranspose(Boundary)

In [22]:
V,CV = larSimplexGrid1([4,4,4])
VIEW(EXPLODE(1.5,1.5,1.5)(MKPOLS((V,CV))))

FV = larSimplexFacets(CV)
EV = larSimplexFacets(FV)
VIEW(EXPLODE(1.5,1.5,1.5)(MKPOLS((V,FV))))
csrSignedBoundaryMat = signedBoundary (V,CV,FV)
boundaryCells_2 = signedBoundaryCells(V,CV,FV)
def swap(l):
    return [l[1],l[0],l[2]]

boundaryFV = [FV[-k] if k<0 else swap(FV[k])for k in boundaryCells_2]
boundary = (V.boundaryFV)
VIEW(EXPLODE(1.5,1.5,1.5)(MKPOLS(boundary)))

NameError: name 'boundaryCells_2' is not defined

![8.PNG](files/Immagini/8.PNG)

![9.PNG](files/Immagini/9.PNG)

In [16]:
V = [[0,0],[1,0],[2,0],[0,1],[1,1],[2,1],[0,2],[1,2],[2,2]]
FV = [[0,1,3],[1,2,4],[2,4,5],[3,4,6],[4,6,7],[5,7,8]]
model = larExtrude1((V,FV),4*[1,2,-3])
VIEW(EXPLODE(1,1,1.2)(MKPOLS(model)))

<pyplasm.xgepy.Hpc; proxy of <Swig Object of type 'std::shared_ptr< Hpc > *' at 0x0000000014451B10> >

![10.PNG](files/Immagini/10.PNG)

In [17]:
VOID = V0,CV0 = [[]],[[0]]

def larSimplexGrid1(shape):
    model = VOID
    for item in shape:
        model = larExtrude1(model,item*[1])
    return model

In [18]:
VIEW(EXPLODE(1.5,1.5,1.5)(MKPOLS(larCuboids([3,2,1]))))
VIEW(EXPLODE(1.5,1.5,1.5)(MKPOLS(larCuboids([3,2,1]))))


<pyplasm.xgepy.Hpc; proxy of <Swig Object of type 'std::shared_ptr< Hpc > *' at 0x0000000014451B40> >

![11.PNG](files/Immagini/11.PNG)
![12.PNG](files/Immagini/12.PNG)

In [19]:
def gridSkeletons(shape):
    gridMap = larGridSkeleton(shape)
    skeletonIds = range ( len(shape)+1)
    skeletons = [ gridMap(id) for id in skeletonIds]
    return skeletons

In [20]:
print "\ngridSkeletons([3]) = \n",gridSkeletons([3])
print "\ngridSkeletons([3,2]) = \n",gridSkeletons([3,2])
print "\ngridSkeletons([3,2,1]) = \n",gridSkeletons([3,2,1])


gridSkeletons([3]) = 
[[[0], [1], [2], [3]], [[0, 1], [1, 2], [2, 3]]]

gridSkeletons([3,2]) = 
[[[0], [1], [2], [3], [4], [5], [6], [7], [8], [9], [10], [11]], [[0, 1], [1, 2], [3, 4], [4, 5], [6, 7], [7, 8], [9, 10], [10, 11], [0, 3], [1, 4], [2, 5], [3, 6], [4, 7], [5, 8], [6, 9], [7, 10], [8, 11]], [[0, 1, 3, 4], [1, 2, 4, 5], [3, 4, 6, 7], [4, 5, 7, 8], [6, 7, 9, 10], [7, 8, 10, 11]]]

gridSkeletons([3,2,1]) = 
[[[0], [1], [2], [3], [4], [5], [6], [7], [8], [9], [10], [11], [12], [13], [14], [15], [16], [17], [18], [19], [20], [21], [22], [23]], [[0, 1], [2, 3], [4, 5], [6, 7], [8, 9], [10, 11], [12, 13], [14, 15], [16, 17], [18, 19], [20, 21], [22, 23], [0, 2], [1, 3], [2, 4], [3, 5], [6, 8], [7, 9], [8, 10], [9, 11], [12, 14], [13, 15], [14, 16], [15, 17], [18, 20], [19, 21], [20, 22], [21, 23], [0, 6], [1, 7], [2, 8], [3, 9], [4, 10], [5, 11], [6, 12], [7, 13], [8, 14], [9, 15], [10, 16], [11, 17], [12, 18], [13, 19], [14, 20], [15, 21], [16, 22], [17, 23]], [[0, 1, 2, 3], [2,